# Generated by Django 4.2.9 on 2024-01-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_alter_appointment_id_alter_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesdata",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
