# Generated by Django 4.2.9 on 2024-01-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_alter_product_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="services/"
            ),
        ),
    ]
