# Generated by Django 4.2 on 2024-03-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_order_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkedout',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
