# Generated by Django 4.2 on 2024-03-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_order_checkedout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkedout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
